config/routes.rb
Rails.application.routes.draw do
  namespace :ckeditor do
    resources :pictures, :only => [:index, :create, :destroy, :edit_images]
    resources :attachments, :only => [:index, :create, :destroy]
  end
	
	match "ckeditor/edit_images" => "ckeditor/pictures#edit_images", :as => 'edit_images'
	match "ckeditor/edit_files" => "ckeditor/attachments#edit_files", :as => 'edit_files'	
end

app/controllers/ckeditor/attachments_controller.rb
class Ckeditor::AttachmentsController < Ckeditor::BaseController

  def index
    @attachments = Ckeditor.file_model.order("id DESC")
    respond_with(@attachments)
  end
  
	def edit_files
		@attachments = Ckeditor.file_model.order("id DESC")
		respond_with(@attachments)
	end

  def create
    @attachment = Ckeditor.file_model.new
	  respond_with_asset(@attachment)
  end
  
  def destroy
    @attachment.destroy
    respond_with(@attachment)
  end
  
  protected
  
    def find_asset
      @attachment = Ckeditor.file_model.find(params[:id])
    end
end

app/controllers/ckeditor/base_controller.rb
class Ckeditor::BaseController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:create]
  
  before_filter :swf_options, :only => [:index, :create]
  before_filter :find_asset, :only => [:destroy]
  
  respond_to :html, :xml, :json
  
  layout "ckeditor"

  protected
    
    def swf_options
      @swf_file_post_name = Ckeditor.swf_file_post_name
      
      if params[:controller] == 'ckeditor/pictures'
        @file_size_limit        = Ckeditor.swf_image_file_size_limit
			  @file_types             = Ckeditor.swf_image_file_types
			  @file_types_description = Ckeditor.swf_image_file_types_description
			  @file_upload_limit      = Ckeditor.swf_image_file_upload_limit
		  else
		    @file_size_limit        = Ckeditor.swf_file_size_limit
		    @file_types             = Ckeditor.swf_file_types
		    @file_types_description = Ckeditor.swf_file_types_description
		    @file_upload_limit      = Ckeditor.swf_file_upload_limit
		  end
      
      @swf_file_post_name ||= 'data'
      @file_size_limit ||= "5 MB"
      @file_types ||= "*.jpg;*.jpeg;*.png;*.gif"
      @file_types_description ||= "Images"
      @file_upload_limit ||= 10
    end
    
    def respond_with_asset(record)
      unless params[:CKEditor].blank?	  
	      params[@swf_file_post_name] = params.delete(:upload)
	    end
	    
	    options = {}
	    
	    params.each do |k, v|
	      key = k.to_s.downcase
	      options[key] = v if record.respond_to?("#{key}=")
	    end
      
      record.attributes = options
      record.user ||= current_user if respond_to?(:current_user)
      
      if record.valid? && record.save
        body = params[:CKEditor].blank? ? record.to_json(:only=>[:id, :type], :methods=>[:url, :content_type, :size, :filename, :format_created_at], :root => "asset") : %Q"<script type='text/javascript'>
          window.parent.CKEDITOR.tools.callFunction(#{params[:CKEditorFuncNum]}, '#{Ckeditor::Utils.escape_single_quotes(record.url_content)}');
        </script>"
        
        render :text => body
      else
        render :nothing => true
      end
    end
end

app/controllers/ckeditor/pictures_controller.rb
class Ckeditor::PicturesController < Ckeditor::BaseController

  def index
    @pictures = Ckeditor.image_model.order("id DESC")
    respond_with(@pictures) 
  end
  
	def edit_images
    @pictures = Ckeditor.image_model.order("id DESC")
    respond_with(@pictures)
	end

  def create
    @picture = Ckeditor.image_model.new
	  respond_with_asset(@picture)
  end
  
  def destroy
    @picture.destroy
    respond_with(@picture)
  end
  
  protected
  
    def find_asset
      @picture = Ckeditor.image_model.find(params[:id])
    end
end

app/helpers/ckeditor/base_helper.rb
module Ckeditor::BaseHelper
  def ckeditor_attachment_path(kind)
    path = case kind
      when :image then Ckeditor.file_manager_image_upload_uri
      when :file  then Ckeditor.file_manager_upload_uri
      else '/ckeditor/attachments'
    end
    
    session_key = Rails.application.config.send(:session_options)[:key]
    
    options = Rails.application.routes.recognize_path(path, :method => :post)
    options[:protocol] = "http://"
    options[session_key] = Rack::Utils.escape(cookies[session_key])
    
    if protect_against_forgery?
      options[request_forgery_protection_token] = Rack::Utils.escape(form_authenticity_token)
    end
    
    url_for(options)
  end
end

app/views/ckeditor/_asset.html.erb
<div class="FCKThumb">
	<% if controller.action_name == 'edit_images' %>
		<%= link_to '', "/ckeditor/pictures/#{asset.id}", :class => 'progressCancel remote-delete'%>
 
		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
			  $('a.remote-delete').click(function() {
			    // we just need to add the key/value pair for the DELETE method
			    // as the second argument to the JQuery $.post() call

	            $.post(this.href, { _method: 'delete' }, null, "script");
							$(this).closest(".FCKThumb").hide();

			    return false;
			  });
			});
		</script>
	<% elsif controller.action_name == 'edit_files' -%>
		<%= link_to '', "/ckeditor/attachments/#{asset.id}", :class => 'progressCancel remote-delete'%>
 
		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
			  $('a.remote-delete').click(function() {
			    // we just need to add the key/value pair for the DELETE method
			    // as the second argument to the JQuery $.post() call

	            $.post(this.href, { _method: 'delete' }, null, "script");
							$(this).closest(".FCKThumb").hide();

			    return false;
			  });
			});
		</script>
	<% end -%>
  <table border="0" cellpadding="0" cellspacing="0" height="100" width="100">
    <tbody>
      <tr>
        <td align="center" valign="middle">
          <%= image_tag(asset.url_thumb, :alt => asset.url_content, :title => asset.filename, :onerror=>"this.src='/javascripts/ckeditor/images/ckfnothumb.gif'", :class=>'image') %>
        </td>
       </tr>
     </tbody>
   </table>
   
   <div class="FCKFileName"><%= asset.filename %></div>
   <div class="FCKFileDate"><%= asset.format_created_at %></div>
   <div class="FCKFileSize"><%= number_to_human_size(asset.size, :precision => 2) %></div>
</div>

app/views/ckeditor/_swfupload.html.erb
<script type="text/javascript">
		var swfu = null;
	
		function init_swfupload() {
		  var params = editor.config['swf_params'];
		
			swfu = new SWFUpload({
				// Backend settings
				upload_url: upload_path,
				post_params: params,
				file_post_name: "<%= @swf_file_post_name %>",

				// Flash file settings
				file_size_limit : "<%= @file_size_limit %>",
				file_types : "<%= @file_types %>",
				file_types_description : "<%= @file_types_description %>",
				file_upload_limit : "<%= @file_upload_limit %>",
				file_queue_limit : 0,

				// The event handler functions are defined in handlers.js
				//swfupload_loaded_handler : swfUploadLoaded,
				file_queued_handler : fileQueued,
				file_queue_error_handler : fileQueueError,
				file_dialog_complete_handler : fileDialogComplete,
				upload_start_handler : uploadStart,
				upload_progress_handler : uploadProgress,
				upload_error_handler : uploadError,
				upload_success_handler : uploadSuccess,
				upload_complete_handler : uploadComplete,
				queue_complete_handler : queueComplete,	// Queue plugin event

				// Button Settings
				button_image_url : "/javascripts/ckeditor/images/select_files.png",
				button_placeholder_id : "spanButtonPlaceholder",
				button_width: 117,
				button_height: 29,
				button_window_mode: SWFUpload.WINDOW_MODE.TRANSPARENT,
				button_cursor: SWFUpload.CURSOR.HAND,
				
				// Flash Settings
				flash_url : "/javascripts/ckeditor/swfupload/swfupload.swf",

				custom_settings : { 
					progressTarget : "divFileProgressContainer"
				},
				
				// Debug settings
				debug: false
			});
		};
</script>

app/views/ckeditor/attachments/edit_files.html.erb
<script src="/javascripts/ckeditor/jquery-1.4.2.min.js" type="text/javascript"></script>

<table width="100%" cellspacing="0" cellpadding="0">
	<tbody>
		<tr>
			<td class="TB_ToolbarSet" id="nv">
				<table border="0" cellspacing="0" cellpadding="0" class="TB_Toolbar">
					<tbody>
						<tr>
							<td>
								<div class="TB_Start">
									&nbsp;
								</div>
							</td>
							<td>
								<div title="Refresh" class="TB_Button">
									<table border="0" cellspacing="0" cellpadding="0">
										<tbody>
											<tr>
												<td>
													<img src="/javascripts/ckeditor/images/refresh.gif" class="TB_Button_Image">
												</td>
												<td class="TB_Button_Text">
													<%= link_to "Refresh", edit_files_path %>
												</td>
												<td>
													<img src="/javascripts/ckeditor/images/spacer.gif" class="TB_Button_Padding">
												</td>
											</tr>
										</tbody>
									</table>
								</div>
							</td>
							<td>
								<div title="List Images" class="TB_Button">
									<table border="0" cellspacing="0" cellpadding="0">
										<tbody>
											<tr>
												<td>
													<img src="/javascripts/ckeditor/images/add.gif" class="TB_Button_Image">
												</td>
												<td class="TB_Button_Text">
													<%= link_to "Back", :back %>
												</td>
												<td>
													<img src="/javascripts/ckeditor/images/spacer.gif" class="TB_Button_Padding">
												</td>
											</tr>
										</tbody>
									</table>
								</div>
							</td>
						</tr>
					</tbody>
				</table>
			</td>
		</tr>
		<tr>
			<td style="height: 100%;" id="qu">
				<div style="overflow:auto; height:550px;" id='container'>
					<%= render :partial => "ckeditor/asset", :collection => @attachments, :as => :asset %>
				</div>
			</td>
		</tr>
	</tbody>
</table>

app/views/ckeditor/attachments/index.html.erb
<script type="text/javascript">	  
var upload_path = "<%=raw ckeditor_attachment_path(:file) %>";

function setUrl(url) 
{  
  CKEDITOR.tools.callFunction(CKEditorFuncNum, url);
  window.close();
}

function uploadButton(button)
{
  var element = $('fj');
  
  if (element.style.display == '')
  {
    element.style.display = 'none';
  }
  else
  {
    element.style.display = '';
  }
}

window.onload = function()
{
  init_swfupload();
  var f = new FileThumb('qu');
  var t = new ToolBar('nv');
  
  var b1 = new Button('Upload New File', 'Upload', 'add.gif');
  var b2 = new Button('Refresh', 'Refresh', 'refresh.gif');
	var b3 = new Button('Edit Images', 'Edit', 'add.gif');
  
  b1.callback = uploadButton;
  b2.callback = function(){ window.location.reload(); }
	b3.callback = function(){ window.location.href = "/ckeditor/edit_files"; }
  
  t.buttons.push(b1);
  t.buttons.push(b2);
  t.buttons.push(b3);
  
  t.init();
}
</script>

<table width="100%" cellspacing="0" cellpadding="0">
	<tbody>
	<tr>
		<td class="TB_ToolbarSet" id="nv"></td>
	</tr>

	<tr id="fj" style='display:none;'>
		<td style="white-space: normal;" class="FCKUploadArea">
			<div class="PopupTitle">
				<span>Upload New Files</span>
			</div>
			<div id="cY">
				<table cellspacing="0" cellpadding="0" style="padding: 10px;">
					<tbody>
					<tr>
						<td>
              <span id='spanButtonPlaceholder'></span>
              <div id="divFileProgressContainer" style="clear:both;"></div>
              
							<%= render :partial => "ckeditor/swfupload" %>
						</td>
					</tr>
				  </tbody>
			  </table>
			  <div class="PopupButtons">
				  <div style="width: 100%;">
					  <table width="100%" cellspacing="0" cellpadding="0">
						  <tbody><tr>
							  <td width="100%"></td>
							  <td nowrap="nowrap">
								  <button onclick="uploadButton()" class="Button"><span ckf:lang="CancelBtn">Cancel</span></button>
							  </td>
						  </tr>
					  </tbody></table>
				  </div>
			  </div>
			</div>
		</td>
	</tr>

	<tr>
		<td style="height: 100%;" id="qu">
		  <div style="overflow:auto; height:550px;" id='container'>
			 <%= render :partial => "ckeditor/asset", :collection => @attachments, :as => :asset %>
		  </div>
		</td>
	</tr>
</tbody>
</table>

app/views/ckeditor/pictures/edit_images.html.erb
<script src="/javascripts/ckeditor/jquery-1.4.2.min.js" type="text/javascript"></script>

<table width="100%" cellspacing="0" cellpadding="0">
	<tbody>
		<tr>
			<td class="TB_ToolbarSet" id="nv">
				<table border="0" cellspacing="0" cellpadding="0" class="TB_Toolbar">
					<tbody>
						<tr>
							<td>
								<div class="TB_Start">
									&nbsp;
								</div>
							</td>
							<td>
								<div title="Refresh" class="TB_Button">
									<table border="0" cellspacing="0" cellpadding="0">
										<tbody>
											<tr>
												<td>
													<img src="/javascripts/ckeditor/images/refresh.gif" class="TB_Button_Image">
												</td>
												<td class="TB_Button_Text">
													<%= link_to "Refresh", edit_images_path %>
												</td>
												<td>
													<img src="/javascripts/ckeditor/images/spacer.gif" class="TB_Button_Padding">
												</td>
											</tr>
										</tbody>
									</table>
								</div>
							</td>
							<td>
								<div title="List Images" class="TB_Button">
									<table border="0" cellspacing="0" cellpadding="0">
										<tbody>
											<tr>
												<td>
													<img src="/javascripts/ckeditor/images/add.gif" class="TB_Button_Image">
												</td>
												<td class="TB_Button_Text">
													<%= link_to "Back", :back %>
												</td>
												<td>
													<img src="/javascripts/ckeditor/images/spacer.gif" class="TB_Button_Padding">
												</td>
											</tr>
										</tbody>
									</table>
								</div>
							</td>
						</tr>
					</tbody>
				</table>
			</td>
		</tr>
		<tr>
			<td style="height: 100%;" id="qu">
				<div style="overflow:auto; height:550px;" id='container'>
					<%= render :partial => "ckeditor/asset", :collection => @pictures, :as => :asset %>
				</div>
			</td>
		</tr>
	</tbody>
</table>

app/views/ckeditor/pictures/index.html.erb
<script type="text/javascript">	  
  var upload_path = "<%=raw ckeditor_attachment_path(:image) %>";
  
  function setUrl(url) 
  {  
    CKEDITOR.tools.callFunction(CKEditorFuncNum, url);
    window.close();
  }
  
  function uploadButton(button)
  {
    var element = $('fj');
    
    if (element.style.display == '')
    {
      element.style.display = 'none';
    }
    else
    {
      element.style.display = '';
    }
  }
  
  window.onload = function()
  {
    init_swfupload();
    var f = new FileThumb('qu');
    var t = new ToolBar('nv');
    
    var b1 = new Button('Upload New File', 'Upload', 'add.gif');
    var b2 = new Button('Refresh', 'Refresh', 'refresh.gif');
		var b3 = new Button('Edit Images', 'Edit', 'add.gif');
    
    b1.callback = uploadButton;
    b2.callback = function(){ window.location.reload(); }
		b3.callback = function(){ window.location.href = "/ckeditor/edit_images"; }
    
    t.buttons.push(b1);
    t.buttons.push(b2);
    t.buttons.push(b3);
    
    t.init();
  }
</script>

<table width="100%" cellspacing="0" cellpadding="0">
	<tbody>
	<tr>
		<td class="TB_ToolbarSet" id="nv"></td>
	</tr>

	<tr id="fj" style='display:none;'>
		<td style="white-space: normal;" class="FCKUploadArea">
			<div class="PopupTitle">
				<span>Upload New Images</span>
			</div>
			<div id="cY">
				<table cellspacing="0" cellpadding="0" style="padding: 10px;">
					<tbody>
					<tr>
						<td>
              <span id='spanButtonPlaceholder'></span>
              <div id="divFileProgressContainer" style="clear:both;"></div>
              
							<%= render :partial => "ckeditor/swfupload" %>
						</td>
					</tr>
				  </tbody>
			  </table>
			  <div class="PopupButtons">
				  <div style="width: 100%;">
					  <table width="100%" cellspacing="0" cellpadding="0">
						  <tbody><tr>
							  <td width="100%"></td>
							  <td nowrap="nowrap">
								  <button onclick="uploadButton()" class="Button"><span ckf:lang="CancelBtn">Cancel</span></button>
							  </td>
						  </tr>
					  </tbody></table>
				  </div>
			  </div>
			</div>
		</td>
	</tr>

	<tr>
		<td style="height: 100%;" id="qu">
		  <div style="overflow:auto; height:550px;" id='container'>
			 <%= render :partial => "ckeditor/asset", :collection => @pictures, :as => :asset %>
		  </div>
		</td>
	</tr>
</tbody>
</table>

app/views/layouts/ckeditor.html.erb
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>CKEditor Files Manager</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="robots" content="noindex, nofollow">
	<link href="/javascripts/ckeditor/css/fck_editor.css" type="text/css" rel="stylesheet">
	<link href="/javascripts/ckeditor/css/fck_dialog.css" type="text/css" rel="stylesheet">
	<link href="/javascripts/ckeditor/css/ckfinder.css" type="text/css" rel="stylesheet">
	<link href="/javascripts/ckeditor/css/swfupload.css" type="text/css" rel="stylesheet">
	
	<script src="/javascripts/ckeditor/swfupload/mootools-1.2.3-core-yc.js" type="text/javascript"></script>
	<script src="/javascripts/ckeditor/swfupload/swfupload.js" type="text/javascript"></script>
	<script src="/javascripts/ckeditor/swfupload/swfupload.queue.js" type="text/javascript"></script>
	<script src="/javascripts/ckeditor/swfupload/fileprogress.js" type="text/javascript"></script>
	<script src="/javascripts/ckeditor/swfupload/handlers.js" type="text/javascript"></script>
	<script src="/javascripts/ckeditor/swfupload/querystring.js" type="text/javascript"></script>
  
  <script type="text/javascript">
    var params = new Querystring();
	  var CKEditorFuncNum = params.get("CKEditorFuncNum");
	  var CKEditorName = params.get("CKEditor");
	  var CKEDITOR = window.opener.CKEDITOR;
	  var editor = CKEDITOR.instances[CKEditorName];
  </script>
</head>
<body style="margin: 0px; padding: 0px;">
  <%= yield %>
</body>
</html>